/*
 * WhatsAPI Go
 * The V2 of WhatsAPI Go
 *
 * The version of the OpenAPI document: 2.0
 * Contact: manjit@sponsorbook.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package whatsapi;

import WhatsAPI.ApiException;
import models.ModelAPIResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for BusinessManagementApi
 */
@Disabled
public class BusinessManagementApiTest {

    private final BusinessManagementApi api = new BusinessManagementApi();

    /**
     * Fetches the catlog.
     *
     * Gets list of all products registered by you.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void instancesInstanceKeyBusinessCatalogGetTest() throws ApiException {
        String instanceKey = null;
        ModelAPIResponse response = api.instancesInstanceKeyBusinessCatalogGet(instanceKey);
        // TODO: test validations
    }

}
