/*
 * WhatsAPI Go
 * The V2 of WhatsAPI Go
 *
 * The version of the OpenAPI document: 2.0
 * Contact: manjit@sponsorbook.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.StructsFileUpload;
import org.openapitools.client.model.StructsTemplateButton;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for StructsTemplateButtonWithMediaPayload
 */
public class StructsTemplateButtonWithMediaPayloadTest {
    private final StructsTemplateButtonWithMediaPayload model = new StructsTemplateButtonWithMediaPayload();

    /**
     * Model tests for StructsTemplateButtonWithMediaPayload
     */
    @Test
    public void testStructsTemplateButtonWithMediaPayload() {
        // TODO: test StructsTemplateButtonWithMediaPayload
    }

    /**
     * Test the property 'buttons'
     */
    @Test
    public void buttonsTest() {
        // TODO: test buttons
    }

    /**
     * Test the property 'contentText'
     */
    @Test
    public void contentTextTest() {
        // TODO: test contentText
    }

    /**
     * Test the property 'footer'
     */
    @Test
    public void footerTest() {
        // TODO: test footer
    }

    /**
     * Test the property 'media'
     */
    @Test
    public void mediaTest() {
        // TODO: test media
    }

    /**
     * Test the property 'to'
     */
    @Test
    public void toTest() {
        // TODO: test to
    }

}
