/*
 * WhatsAPI Go
 * The V2 of WhatsAPI Go
 *
 * The version of the OpenAPI document: 2.0
 * Contact: manjit@sponsorbook.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import models.StructsReplyButton;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for StructsButtonMessagePayload
 */
public class StructsButtonMessagePayloadTest {
    private final StructsButtonMessagePayload model = new StructsButtonMessagePayload();

    /**
     * Model tests for StructsButtonMessagePayload
     */
    @Test
    public void testStructsButtonMessagePayload() {
        // TODO: test StructsButtonMessagePayload
    }

    /**
     * Test the property 'buttons'
     */
    @Test
    public void buttonsTest() {
        // TODO: test buttons
    }

    /**
     * Test the property 'footerText'
     */
    @Test
    public void footerTextTest() {
        // TODO: test footerText
    }

    /**
     * Test the property 'headerText'
     */
    @Test
    public void headerTextTest() {
        // TODO: test headerText
    }

    /**
     * Test the property 'text'
     */
    @Test
    public void textTest() {
        // TODO: test text
    }

    /**
     * Test the property 'to'
     */
    @Test
    public void toTest() {
        // TODO: test to
    }

}
