/*
 * WhatsAPI Go
 * The V2 of WhatsAPI Go
 *
 * The version of the OpenAPI document: 2.0
 * Contact: manjit@sponsorbook.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for StructsFileUpload
 */
public class StructsFileUploadTest {
    private final StructsFileUpload model = new StructsFileUpload();

    /**
     * Model tests for StructsFileUpload
     */
    @Test
    public void testStructsFileUpload() {
        // TODO: test StructsFileUpload
    }

    /**
     * Test the property 'directPath'
     */
    @Test
    public void directPathTest() {
        // TODO: test directPath
    }

    /**
     * Test the property 'fileEncSha256'
     */
    @Test
    public void fileEncSha256Test() {
        // TODO: test fileEncSha256
    }

    /**
     * Test the property 'fileLength'
     */
    @Test
    public void fileLengthTest() {
        // TODO: test fileLength
    }

    /**
     * Test the property 'fileSha256'
     */
    @Test
    public void fileSha256Test() {
        // TODO: test fileSha256
    }

    /**
     * Test the property 'mediaKey'
     */
    @Test
    public void mediaKeyTest() {
        // TODO: test mediaKey
    }

    /**
     * Test the property 'mimeType'
     */
    @Test
    public void mimeTypeTest() {
        // TODO: test mimeType
    }

    /**
     * Test the property 'url'
     */
    @Test
    public void urlTest() {
        // TODO: test url
    }

}
