/*
 * WhatsAPI Go
 * The V2 of WhatsAPI Go
 *
 * The version of the OpenAPI document: 2.0
 * Contact: manjit@sponsorbook.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import models.StructsTemplateButton;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for StructsTemplateButtonPayload
 */
public class StructsTemplateButtonPayloadTest {
    private final StructsTemplateButtonPayload model = new StructsTemplateButtonPayload();

    /**
     * Model tests for StructsTemplateButtonPayload
     */
    @Test
    public void testStructsTemplateButtonPayload() {
        // TODO: test StructsTemplateButtonPayload
    }

    /**
     * Test the property 'buttons'
     */
    @Test
    public void buttonsTest() {
        // TODO: test buttons
    }

    /**
     * Test the property 'contentText'
     */
    @Test
    public void contentTextTest() {
        // TODO: test contentText
    }

    /**
     * Test the property 'footer'
     */
    @Test
    public void footerTest() {
        // TODO: test footer
    }

    /**
     * Test the property 'header'
     */
    @Test
    public void headerTest() {
        // TODO: test header
    }

    /**
     * Test the property 'to'
     */
    @Test
    public void toTest() {
        // TODO: test to
    }

}
