/*
 * WhatsAPI Go
 * The V2 of WhatsAPI Go
 *
 * The version of the OpenAPI document: 2.0
 * Contact: manjit@sponsorbook.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import WhatsAPI.JSON;

/**
 * GroupInviteMessagePayload
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-11-30T17:55:55.962510800+05:30[Asia/Calcutta]")
public class GroupInviteMessagePayload {
  public static final String SERIALIZED_NAME_CAPTION = "caption";
  @SerializedName(SERIALIZED_NAME_CAPTION)
  private String caption;

  public static final String SERIALIZED_NAME_EXPIRY_MINUTES = "expiry_minutes";
  @SerializedName(SERIALIZED_NAME_EXPIRY_MINUTES)
  private Integer expiryMinutes;

  public static final String SERIALIZED_NAME_INVITE_CODE = "invite_code";
  @SerializedName(SERIALIZED_NAME_INVITE_CODE)
  private String inviteCode;

  public static final String SERIALIZED_NAME_TO = "to";
  @SerializedName(SERIALIZED_NAME_TO)
  private String to;

  public GroupInviteMessagePayload() {
  }

  public GroupInviteMessagePayload caption(String caption) {
    
    this.caption = caption;
    return this;
  }

   /**
   * Get caption
   * @return caption
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getCaption() {
    return caption;
  }


  public void setCaption(String caption) {
    this.caption = caption;
  }


  public GroupInviteMessagePayload expiryMinutes(Integer expiryMinutes) {
    
    this.expiryMinutes = expiryMinutes;
    return this;
  }

   /**
   * Get expiryMinutes
   * @return expiryMinutes
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getExpiryMinutes() {
    return expiryMinutes;
  }


  public void setExpiryMinutes(Integer expiryMinutes) {
    this.expiryMinutes = expiryMinutes;
  }


  public GroupInviteMessagePayload inviteCode(String inviteCode) {
    
    this.inviteCode = inviteCode;
    return this;
  }

   /**
   * Get inviteCode
   * @return inviteCode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getInviteCode() {
    return inviteCode;
  }


  public void setInviteCode(String inviteCode) {
    this.inviteCode = inviteCode;
  }


  public GroupInviteMessagePayload to(String to) {
    
    this.to = to;
    return this;
  }

   /**
   * Get to
   * @return to
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getTo() {
    return to;
  }


  public void setTo(String to) {
    this.to = to;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GroupInviteMessagePayload groupInviteMessagePayload = (GroupInviteMessagePayload) o;
    return Objects.equals(this.caption, groupInviteMessagePayload.caption) &&
        Objects.equals(this.expiryMinutes, groupInviteMessagePayload.expiryMinutes) &&
        Objects.equals(this.inviteCode, groupInviteMessagePayload.inviteCode) &&
        Objects.equals(this.to, groupInviteMessagePayload.to);
  }

  @Override
  public int hashCode() {
    return Objects.hash(caption, expiryMinutes, inviteCode, to);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GroupInviteMessagePayload {\n");
    sb.append("    caption: ").append(toIndentedString(caption)).append("\n");
    sb.append("    expiryMinutes: ").append(toIndentedString(expiryMinutes)).append("\n");
    sb.append("    inviteCode: ").append(toIndentedString(inviteCode)).append("\n");
    sb.append("    to: ").append(toIndentedString(to)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("caption");
    openapiFields.add("expiry_minutes");
    openapiFields.add("invite_code");
    openapiFields.add("to");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to GroupInviteMessagePayload
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!GroupInviteMessagePayload.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in GroupInviteMessagePayload is not found in the empty JSON string", GroupInviteMessagePayload.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!GroupInviteMessagePayload.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `GroupInviteMessagePayload` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }
      if ((jsonObj.get("caption") != null && !jsonObj.get("caption").isJsonNull()) && !jsonObj.get("caption").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `caption` to be a primitive type in the JSON string but got `%s`", jsonObj.get("caption").toString()));
      }
      if ((jsonObj.get("invite_code") != null && !jsonObj.get("invite_code").isJsonNull()) && !jsonObj.get("invite_code").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `invite_code` to be a primitive type in the JSON string but got `%s`", jsonObj.get("invite_code").toString()));
      }
      if ((jsonObj.get("to") != null && !jsonObj.get("to").isJsonNull()) && !jsonObj.get("to").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `to` to be a primitive type in the JSON string but got `%s`", jsonObj.get("to").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!GroupInviteMessagePayload.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'GroupInviteMessagePayload' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<GroupInviteMessagePayload> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(GroupInviteMessagePayload.class));

       return (TypeAdapter<T>) new TypeAdapter<GroupInviteMessagePayload>() {
           @Override
           public void write(JsonWriter out, GroupInviteMessagePayload value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public GroupInviteMessagePayload read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of GroupInviteMessagePayload given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of GroupInviteMessagePayload
  * @throws IOException if the JSON string is invalid with respect to GroupInviteMessagePayload
  */
  public static GroupInviteMessagePayload fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, GroupInviteMessagePayload.class);
  }

 /**
  * Convert an instance of GroupInviteMessagePayload to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

