/*
 * WhatsAPI Go
 * The V2 of WhatsAPI Go
 *
 * The version of the OpenAPI document: 2.0
 * Contact: manjit@sponsorbook.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.MainAPIResponse;
import org.openapitools.client.model.StructsUserInfoPayload;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for MiscellaneousApi
 */
@Disabled
public class MiscellaneousApiTest {

    private final MiscellaneousApi api = new MiscellaneousApi();

    /**
     * Get profile pic.
     *
     * Returns the profile pic of the given user.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void instancesInstanceKeyMiscProfilePicGetTest() throws ApiException {
        String instanceKey = null;
        String jid = null;
        MainAPIResponse response = api.instancesInstanceKeyMiscProfilePicGet(instanceKey, jid);
        // TODO: test validations
    }

    /**
     * Fetches the users info.
     *
     * Gets the user info for the given user ids. This does not checks if user is registered or not
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void instancesInstanceKeyMiscUserInfoPostTest() throws ApiException {
        String instanceKey = null;
        StructsUserInfoPayload data = null;
        MainAPIResponse response = api.instancesInstanceKeyMiscUserInfoPost(instanceKey, data);
        // TODO: test validations
    }

}
